### ISSUE TITLE
Mods

### ISSUE THREAD

**Issue by mora145** [alextd/Rimworld-SmartMedicine#15]
Hey man, I contact you in this way because I can not get another one. Do you know any guides or courses to learn how to make the rimworld mods? I know a bit about C #, but not how to apply it to Rim.

My mail yeshualicett135@gmail.com

**Comment by alextd** [comment]
Well to get you started there is a RimWorld discord with modding resources:

https://ludeon.com/forums/index.php?topic=27941.0
